"""Mixed Traffic Send Tool — sends multi-protocol, multi-stream traffic via Scapy.

Takes a Traffic Description JSON (generated by the LLM) that describes multiple
concurrent traffic streams with different protocols and percentages. Enforces
strict security: IP.dst overwrite, protocol whitelist, no eval injection.
"""
import json
import random
import socket
import time
from typing import Any

from .ping_rtt_tool import validate_target
from .traffic_send_tool import _create_raw_socket

try:
    from scapy.all import IP, TCP, UDP, ICMP, DNS, Raw, send
    from scapy.all import DNSQR, DNSRR
    HAS_SCAPY = True
except ImportError:
    HAS_SCAPY = False

# ── Parameter limits ──────────────────────────────────────────
MAX_PPS = 20000
MAX_DURATION_S = 20
MAX_IAT_JITTER_MS = 20
MIN_STREAMS = 1
MAX_STREAMS = 100
MAX_JSON_LENGTH = 10000

# ── Protocol whitelist (NO eval, NO getattr on user input) ────
PROTO_CLASS_MAP: dict[str, Any] = {
    "IP": IP,
    "TCP": TCP,
    "UDP": UDP,
    "ICMP": ICMP,
    "DNS": DNS,
    "Raw": Raw,
}

NESTED_FIELD_MAP: dict[tuple[str, str], Any] = {
    ("DNS", "qd"): DNSQR,
    ("DNS", "an"): DNSRR,
    ("DNS", "ns"): DNSRR,
    ("DNS", "ar"): DNSRR,
}

# ── Dangerous pattern detection ────────────────────────────────
FORBIDDEN_PATTERNS = [
    "__import__", "eval(", "exec(", "compile(",
    "os.", "subprocess", "sys.", "shutil",
    "open(", "file(", "input(",
    "__",
]


def _check_dangerous_values(obj: Any, sid: str, proto: str) -> None:
    """Recursively scan field values for injection patterns."""
    if isinstance(obj, str):
        lowered = obj.lower()
        for pattern in FORBIDDEN_PATTERNS:
            if pattern in lowered:
                raise ValueError(
                    f"stream '{sid}', protocol '{proto}': "
                    f"forbidden pattern '{pattern}' in value"
                )
    elif isinstance(obj, dict):
        for key, val in obj.items():
            _check_dangerous_values(key, sid, proto)
            _check_dangerous_values(val, sid, proto)
    elif isinstance(obj, list):
        for item in obj:
            _check_dangerous_values(item, sid, proto)


def _resolve_nested_fields(proto_name: str, fields: dict) -> dict[str, Any]:
    """Resolve nested dict fields to Scapy constructor instances.

    e.g. {"qd": {"qname": "example.com.", "qtype": "A"}} for DNS
    becomes {"qd": DNSQR(qname="example.com.", qtype="A")}.
    """
    result: dict[str, Any] = {}
    for key, value in fields.items():
        nested_key = (proto_name, key)
        if nested_key in NESTED_FIELD_MAP:
            nested_cls = NESTED_FIELD_MAP[nested_key]
            if isinstance(value, dict):
                try:
                    result[key] = nested_cls(**value)
                except (KeyError, TypeError, ValueError) as e:
                    raise ValueError(
                        f"stream field '{proto_name}.{key}': invalid value for "
                        f"{nested_cls.__name__}: {e}"
                    ) from e
            elif isinstance(value, list):
                result[key] = [nested_cls(**item) for item in value]
            else:
                raise ValueError(
                    f"stream field '{proto_name}.{key}' requires a dict or list[dict] value, "
                    f"got {type(value).__name__}"
                )
        elif isinstance(value, dict):
            raise ValueError(
                f"stream field '{proto_name}.{key}': nested dict not allowed — "
                f"unknown nested constructor for ({proto_name}, {key})"
            )
        else:
            result[key] = value
    return result


def build_packet_template(stream: dict, dst_ip: str) -> Any:
    """Dynamically construct a Scapy packet template from a stream spec.

    Uses ``/`` operator to stack layers bottom-up. IP.dst is FORCE-OVERWRITTEN
    to dst_ip regardless of what the LLM embeds in the JSON.
    """
    layers = []
    for proto_name in stream["protocol_stack"]:
        cls = PROTO_CLASS_MAP[proto_name]
        raw_kwargs = stream.get("fields", {}).get(proto_name, {})
        resolved = _resolve_nested_fields(proto_name, raw_kwargs)

        if proto_name == "IP":
            resolved["dst"] = dst_ip

        layers.append(cls(**resolved))

    if not layers:
        raise ValueError(f"stream '{stream.get('stream_id', '?')}': empty protocol_stack")

    pkt = layers[0]
    for layer in layers[1:]:
        pkt = pkt / layer
    return pkt


def validate_traffic_spec(spec: dict) -> list[dict]:
    """Validate the parsed traffic spec dict. Returns validated stream list.

    Raises ValueError with a descriptive message on any violation.
    """
    streams = spec.get("streams")

    if not isinstance(streams, list):
        raise ValueError("traffic spec must have a 'streams' array")

    if not (MIN_STREAMS <= len(streams) <= MAX_STREAMS):
        raise ValueError(
            f"stream count {len(streams)} not in [{MIN_STREAMS}, {MAX_STREAMS}]"
        )

    stream_ids: set[str] = set()
    total_pct = 0

    for stream in streams:
        if not isinstance(stream, dict):
            raise ValueError("each stream must be a dict")

        sid = stream.get("stream_id")
        if not sid or not isinstance(sid, str):
            raise ValueError("each stream must have a non-empty string stream_id")
        if sid in stream_ids:
            raise ValueError(f"duplicate stream_id: '{sid}'")
        stream_ids.add(sid)

        stack = stream.get("protocol_stack")
        if not isinstance(stack, list) or len(stack) == 0:
            raise ValueError(f"stream '{sid}': protocol_stack must be a non-empty list")
        for proto in stack:
            if not isinstance(proto, str) or proto not in PROTO_CLASS_MAP:
                raise ValueError(
                    f"stream '{sid}': protocol '{proto}' not in whitelist "
                    f"({sorted(PROTO_CLASS_MAP.keys())})"
                )

        fields = stream.get("fields", {})
        if not isinstance(fields, dict):
            raise ValueError(f"stream '{sid}': fields must be a dict")
        for proto_name, field_dict in fields.items():
            if not isinstance(field_dict, dict):
                raise ValueError(
                    f"stream '{sid}': fields.{proto_name} must be a dict"
                )
            _check_dangerous_values(field_dict, sid, proto_name)

        pct = stream.get("percentage")
        if not isinstance(pct, int) or not (1 <= pct <= 100):
            raise ValueError(
                f"stream '{sid}': percentage must be int 1-100, got {pct}"
            )
        total_pct += pct

    if total_pct != 100:
        raise ValueError(
            f"stream percentages sum to {total_pct}, must be 100"
        )

    return streams


def mixed_traffic_send_tool(
    dst_ip: str,
    traffic_spec_json: str,
    duration_s: int = 5,
    pps: int = 100,
    iface: str | None = None,
    verbose: bool = False,
) -> dict[str, Any]:
    """Send mixed-protocol traffic to a target according to a traffic spec.

    Args:
        dst_ip: Target IP address (must be in allowlist). IP.dst in the JSON
                is ignored — this value overwrites it for safety.
        traffic_spec_json: JSON string describing traffic streams.
        duration_s: Send duration in seconds (max 20).
        pps: Total packets per second across all streams (max 20000).
        iface: Optional network interface for send().
        verbose: Enable Scapy verbose output.

    Returns:
        Dict with success, params, packets_sent (total + per_stream),
        elapsed_s, effective_pps.
    """
    if not HAS_SCAPY:
        raise ImportError("Scapy is required for mixed_traffic_send_tool")

    # 1. Validate target IP
    validate_target(dst_ip)

    # 2. Clamp pps and duration
    if not (1 <= pps <= MAX_PPS):
        raise ValueError(f"pps ({pps}) must be in [1, {MAX_PPS}]")
    if not (1 <= duration_s <= MAX_DURATION_S):
        raise ValueError(f"duration_s ({duration_s}) must be in [1, {MAX_DURATION_S}]")

    # 3. Check JSON length
    if len(traffic_spec_json) > MAX_JSON_LENGTH:
        raise ValueError(
            f"traffic_spec_json too long ({len(traffic_spec_json)} chars, "
            f"max {MAX_JSON_LENGTH})"
        )

    # 4. Parse JSON
    try:
        spec = json.loads(traffic_spec_json)
    except json.JSONDecodeError as e:
        raise ValueError(f"Invalid JSON in traffic_spec_json: {e}")

    # 5. Validate spec and build packet templates → serialize to bytes
    streams = validate_traffic_spec(spec)
    templates: list[tuple[str, bytes, int]] = []
    scapy_templates: list[tuple[str, Any, int]] = []  # for fallback
    for stream in streams:
        pkt = build_packet_template(stream, dst_ip)
        templates.append((stream["stream_id"], bytes(pkt), stream["percentage"]))
        scapy_templates.append((stream["stream_id"], pkt, stream["percentage"]))

    # 6. Build CDF for weighted random sampling
    cumulative: list[int] = []
    running = 0
    for _, _, pct in templates:
        running += pct
        cumulative.append(running)

    # 7. Create raw socket (fall back to Scapy if permission denied)
    raw_sock = _create_raw_socket()
    use_raw = raw_sock is not None

    # 8. Send loop
    per_stream_counts: dict[str, int] = {sid: 0 for sid, _, _ in templates}
    total_sent = 0
    base_inter = 1.0 / pps
    start_time = time.time()
    deadline = start_time + duration_s
    next_send = start_time

    try:
        while time.time() < deadline:
            now = time.time()
            if now >= next_send:
                r = random.randint(1, 100)
                for idx, c in enumerate(cumulative):
                    if r <= c:
                        sid, data, _ = templates[idx]
                        fallback_pkt = scapy_templates[idx][1]
                        break
                else:
                    sid, data, _ = templates[-1]
                    fallback_pkt = scapy_templates[-1][1]

                if use_raw:
                    raw_sock.sendto(data, (dst_ip, 0))  # type: ignore[union-attr]
                else:
                    send(fallback_pkt, verbose=verbose, iface=iface)

                per_stream_counts[sid] += 1
                total_sent += 1

                jitter_s = random.uniform(-MAX_IAT_JITTER_MS, MAX_IAT_JITTER_MS) / 1000.0
                next_send = time.time() + max(base_inter + jitter_s, 0)
            else:
                time.sleep(0.0001)
    except KeyboardInterrupt:
        pass
    finally:
        if raw_sock is not None:
            raw_sock.close()

    elapsed = time.time() - start_time
    effective_pps = round(total_sent / elapsed, 2) if elapsed > 0 else 0.0

    return {
        "success": True,
        "params": {
            "dst_ip": dst_ip,
            "duration_s": duration_s,
            "pps": pps,
            "streams": [
                {"stream_id": s["stream_id"], "percentage": s["percentage"]}
                for s in streams
            ],
        },
        "packets_sent": {
            "total": total_sent,
            "per_stream": per_stream_counts,
        },
        "elapsed_s": round(elapsed, 4),
        "effective_pps": effective_pps,
        "raw_socket": use_raw,
        "errors": [],
    }


if __name__ == "__main__":
    import sys
    if len(sys.argv) < 3:
        print("Usage: python mixed_traffic_tool.py <dst_ip> <traffic_spec_json> [pps] [duration_s]")
        sys.exit(1)

    result = mixed_traffic_send_tool(
        dst_ip=sys.argv[1],
        traffic_spec_json=sys.argv[2],
        pps=int(sys.argv[3]) if len(sys.argv) > 3 else 10,
        duration_s=int(sys.argv[4]) if len(sys.argv) > 4 else 2,
    )
    print(json.dumps(result, indent=2, default=str))
